language: java

jdk:
  - oraclejdk8

dist: trusty

before_install: cd onedev-main

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - cd server-core
  - mvn test -B
  - cd ..
  - cd server-product
  - mvn test -B
  - cd ..
  - cd server-plugin/server-executor-docker
  - mvn test -B
  - cd ../..
  - cd server-plugin/server-plugin-authenticator-ldap
  - mvn test -B

branches:
  only: 
    - main